name: Testing Core Requirements
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Determine changed files
      id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: json
    - name: Run jest
      run: |
        npx http-server --silent --port 8080 &
        npm test --color=true
